cbf_safety_filter_node:
  ros__parameters:
    d_safe: 0.35
    alpha: 2.0
    l_offset: 0.2
    v_max: 0.8
    v_min: -0.3
    w_max: 1.0
    costmap_topic: "/local_costmap/costmap"
    cmd_vel_nav_topic: "/cmd_vel_final" 
    cmd_vel_out_topic: "/cmd_vel"
    robot_base_frame: "base_link"
    obstacle_lethal_threshold: 90
